PCT Iterative
JosueCab/wekatfg pull request #3
Opened 2023-05-01 18:07 UTC by JosueCab

PCT Iterative egiteko, aurreko funtzionalinateekin

2023-05-02 07:56 UTC, txpzdf approved these changes

2023-05-03 15:06 UTC, txpzdf requested changes

2023-05-03 15:06 UTC, txpzdf commented on src/main/java/weka/classifiers/trees/j48It/C45PruneableClassifierTreeIt.java
> +		list.add(new Object[] { data, this, null, 0, 0}); // The parent node is considered level 0
Beste osagai bat gehitu duzu zerrendan, baina, berriz, gero ez da erabiltzen, ezta?
Berez uste dut ez dela behar

2023-05-03 15:06 UTC, txpzdf commented on src/main/java/weka/classifiers/trees/j48It/C45PruneableClassifierTreeIt.java
> +		int usedNodes = 0;
Zer iruditzen 'usedNodes' baino 'extendedNodes' edo 'expandedNodes' edo inkluso 'internalNodes' (hostoetatik bereizteko) jartzen badugu?

2023-05-03 16:16 UTC, JosueCab commented on src/main/java/weka/classifiers/trees/j48It/C45PruneableClassifierTreeIt.java
> +		list.add(new Object[] { data, this, null, 0, 0}); // The parent node is considered level 0
Egia, jarri nuen beste gauza bat frogatzeko eta ahaztu zitzaidan kentzea.

2023-05-09 15:01 UTC, txpzdf requested changes

2023-05-09 15:01 UTC, txpzdf commented on src/main/java/weka/classifiers/trees/J48ItPartiallyConsolidated.java
> +	protected int m_ITPCTmaximumCriteria = 99999;
Goizean esan dugun bezala, hau ez dugu behar; berezko m_PCTBconsolidationPercent atributuarekin lortu dezakegu maximoa, behin zuhaitz kontsolidatu osoaren barneko adabegi kopurura ezagutzen dugunean.

2023-05-09 15:01 UTC, txpzdf commented on src/main/java/weka/classifiers/trees/j48ItPartiallyConsolidated/C45ItPartiallyConsolidatedPruneableClassifierTree.java
>  	public void buildTree(Instances data, Instances[] samplesVector, boolean keepData) throws Exception {
Begiratu dut honen kodea gainetik eta, guztiz ziur egon gabe, itxura ona hartzen diot benetan.
Hala ere, goizean esan dugun bezala, klase honen buildClassifier() funtzioa berdefinitu beharko litzateke orain (J48It-en ez genuen egin behar) eta ondokoa egin beharrean (ahaztu oraingoz collapse() eta prune()):

- buildTree()
- leavePartiallyConsolidated()
- applyBagging()

zera egin beharko genuke:

- buildTree()
- m_maximumCriteria = Eskuratu zuhaitzaren barneko adabegi kopurua (leavePartiallyConsolidated()-en egiten zen bezala)
- buildTreeIt()
- applyBagging()

Bai?

2023-05-15 12:47 UTC, JosueCab commented on src/main/java/weka/classifiers/trees/j48ItPartiallyConsolidated/C45ItPartiallyConsolidatedPruneableClassifierTree.java
>  	public void buildTree(Instances data, Instances[] samplesVector, boolean keepData) throws Exception {
PriorityCriteria malaz maila bada berdina egin beharko zen? Edo adabegi kopurua lortu beharrean, maila kopurua eskuratu behar da?

2023-05-15 13:54 UTC, txpzdf commented on src/main/java/weka/classifiers/trees/j48ItPartiallyConsolidated/C45ItPartiallyConsolidatedPruneableClassifierTree.java
>  	public void buildTree(Instances data, Instances[] samplesVector, boolean keepData) throws Exception {
Bai, karo, maila kopurua eskuratu beharko litzateke, bai. Berez, maila kopuru maximoa esango nuke, hau da, errotik ateratzen den adarrik luzenaren luzera, ezta?

2023-05-15 14:58 UTC, JosueCab commented on src/main/java/weka/classifiers/trees/j48ItPartiallyConsolidated/C45ItPartiallyConsolidatedPruneableClassifierTree.java
>  	public void buildTree(Instances data, Instances[] samplesVector, boolean keepData) throws Exception {
Eta badakizu zuhaitzaren mailak kalkulatzen dituen metodorik dagoen? Edo sortu behar dut?

2023-05-15 15:41 UTC, txpzdf commented on src/main/java/weka/classifiers/trees/j48ItPartiallyConsolidated/C45ItPartiallyConsolidatedPruneableClassifierTree.java
>  	public void buildTree(Instances data, Instances[] samplesVector, boolean keepData) throws Exception {
J48k erabiltzen duen ClassifierTree klasean badaude numLeaves() eta numNodes() funtzioak, Hosto edo adar kopurua eta adabegi kopurua (hosto + barneko adabegi) kalkulatzeko. Horiek pista bat emango dizute, adarrik luzeena kalkulatzeko, ezta? Edo?

2023-05-16 15:57 UTC, JosueCab commented
Sortu dut ClassifierTree klasean numLevels() funtzioa mailak kalkulatzeko

2023-05-17 15:51 UTC, txpzdf requested changes

2023-05-17 15:51 UTC, txpzdf commented on src/main/java/weka/classifiers/trees/j48/ClassifierTree.java
> +	public int numLevels() {
Nik mugitu dut funtzioa C45ItPartiallyConsolidatedPruneableClassifierTree klasera eta m_sons[i].numLevels() casting-a jarri diot eta ez dit errorerik ematen:
`				int nl = ((C45ItPartiallyConsolidatedPruneableClassifierTree)m_sons[i]).numLevels();`

2023-05-17 15:51 UTC, txpzdf commented on src/main/java/weka/classifiers/trees/j48ItPartiallyConsolidated/C45ItPartiallyConsolidatedPruneableClassifierTree.java
> + * @author JesÃºs M. PÃ©rez (txus.perez@ehu.eus)
Kontuz!

2023-05-23 10:45 UTC, JosueCab commented on src/main/java/weka/classifiers/trees/j48/ClassifierTree.java
> +	public int numLevels() {
Niri kodean ez dit errorea ematen, baina exekutatzean ezin dela casting-a egiten esaten dit.

2023-05-23 15:00 UTC, txpzdf commented on src/main/java/weka/classifiers/trees/j48/ClassifierTree.java
> +	public int numLevels() {
Azkenean, konpondu duzu hau, orduan?

2023-05-23 15:17 UTC, JosueCab commented on src/main/java/weka/classifiers/trees/j48/ClassifierTree.java
> +	public int numLevels() {
Ez, momentuz zegoen bezala utzi dut, ea lortzen dudan aldatzea.

2023-05-23 15:29 UTC, txpzdf commented
Kaixo!
Eta zergatik niri funtzionatzen dit?

Daukadana pasatzen dizut...

Txus

On Tue, May 23, 2023 at 5:18 PM JosueCab ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/main/java/weka/classifiers/trees/j48/ClassifierTree.java
> <https://github.com/JosueCab/wekatfg/pull/3#discussion_r1202526876>:
>
> > +
> +		if (!m_isLeaf) {
> +			for (i = 0; i < m_sons.length; i++) {
> +				no = no + m_sons[i].numNodes();
> +			}
> +		}
> +
> +		return no;
> +	}
> +
> +	/**
> +	 * Returns number of levels in tree structure.
> +	 *
> +	 * @return the number of levels
> +	 */
> +	public int numLevels() {
>
> Ez, momentuz zegoen bezala utzi dut, ea lortzen dudan aldatzea.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JosueCab/wekatfg/pull/3#discussion_r1202526876>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO64PHW4DVTQ3K452JR66TLXHTIKRANCNFSM6AAAAAAXSASNN4>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-05-24 07:11 UTC, txpzdf commented on src/main/java/weka/classifiers/trees/j48PartiallyConsolidated/C45PartiallyConsolidatedPruneableClassifierTree.java
> +import weka.classifiers.trees.j48ItPartiallyConsolidated.C45ItPartiallyConsolidatedPruneableClassifierTree;
Hau da aldaketa bakarra fitxategi honetan? Izango da proba batena eta orain soberan egongo da, ezta?

2023-05-24 07:13 UTC, txpzdf commented on src/main/java/weka/classifiers/trees/j48ItPartiallyConsolidated/C45ItPartiallyConsolidatedPruneableClassifierTree.java
> +				m_priorityCriteria = J48It.Original; // Change the criteria to ORIGINAL to build the tree without restrictions
Ez dut ikusten honen beharrik baina deskargatuko dut kodea eta hobeto begiratuko dut.

2023-05-24 07:13 UTC, txpzdf approved these changes

2023-05-24 09:58 UTC, JosueCab commented on src/main/java/weka/classifiers/trees/j48PartiallyConsolidated/C45PartiallyConsolidatedPruneableClassifierTree.java
> +import weka.classifiers.trees.j48ItPartiallyConsolidated.C45ItPartiallyConsolidatedPruneableClassifierTree;
Refactorizazioa da, It aurrerago egoteko

2023-05-24 10:00 UTC, JosueCab commented on src/main/java/weka/classifiers/trees/j48ItPartiallyConsolidated/C45ItPartiallyConsolidatedPruneableClassifierTree.java
> +				m_priorityCriteria = J48It.Original; // Change the criteria to ORIGINAL to build the tree without restrictions
Konpontzeko burutu zaidan aukera da, agian badago beste modu errazagoa, baina ez zait okurritzen

2023-05-24 12:51 UTC, txpzdf commented
Kaixo Josué!
Mugitu dut numLevels() C45ItPartiallyConsolidatedPruneableClassifierTree
klasetik C45PartiallyConsolidatedPruneableClassifierTree klasera eta
badabil zuzenean super.buildTree()-ri deituta.
Bestalde, konturatu naiz C45ItPartiallyConsolidatedPruneableClassifierTree
klasean ez diogula buildTree-ri izena aldatu behar, buildTreeIt izateko.
Nahikoa da buildTree izena izanda (C45ItPruneableClassifierTree klasean,
J48It-rako, egin genuen bezala).
Atxikita bidaltzen dizkizut bi fitxategiak. Probatu zuk ea gonbintzitzen
zaituen eta horrela bada, kendu iruzkinak eta abar.
Gero arte
Txus

On Wed, May 24, 2023 at 12:00 PM JosueCab ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> src/main/java/weka/classifiers/trees/j48ItPartiallyConsolidated/C45ItPartiallyConsolidatedPruneableClassifierTree.java
> <https://github.com/JosueCab/wekatfg/pull/3#discussion_r1203829379>:
>
> > @@ -104,8 +104,15 @@ public void buildClassifier(Instances data, Instances[] samplesVector, float con
>  			System.out.println("it buildClassifer");
>  			
>  			if (consolidationNumberHowToSet == J48ItPartiallyConsolidated.ConsolidationNumber_Percentage) {
> -				buildTree(data, samplesVector, m_subtreeRaising || !m_cleanup);
> -
> +				
> +				int copyPriorityCriteria = m_priorityCriteria; // keep the priority
> +				
> +				m_priorityCriteria = J48It.Original; // Change the criteria to ORIGINAL to build the tree without restrictions
>
> Konpontzeko burutu zaidan aukera da
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JosueCab/wekatfg/pull/3#discussion_r1203829379>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO64PHQDY3Y67ZFWHKYN3ODXHXL4LANCNFSM6AAAAAAXSASNN4>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-05-31 12:48 UTC, txpzdf approved these changes
Ados

2023-05-31 16:48 UTC, JosueCab commented
Azken commit-a soberan dago

2023-05-31 16:48 UTC, merged